spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/nexcart_product_db
    username: root
    password: Csprasanna@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
